#!/bin/bash
dbname=facetablet
dbuser=facever
dbpass=facever
table1=recog_user
table2=client
table3=client_token
table4=trx_log

# file=<path-to-file>
file="rkb8.pass"
while IFS= read line
do
    remotepass=$line
    sshpass -p $remotepass ssh -p 25025 ubuntu@210.210.156.73 "PGPASSWORD=$dbpass pg_dump \
    -U $dbuser --format=custom -h localhost $dbname -t $table1 -t $table2 -t $table3" | \
    PGPASSWORD=$dbpass pg_restore --clean -U $dbuser -d $dbname
done < "$file"
