#!/bin/bash
tmux new -s backend-go -d

## run main backend-go app
tmux send-keys -t backend-go:0 "cd $HOME/workspace/fr-backend-go/
go build main.go && ./main" C-m

## run decodebase64 microservice
tmux new-window -t backend-go:1
tmux send-keys -t backend-go:1 "cd $HOME/workspace/fr-backend-go/microservices/decode_base64/golang/
go build decodeBase64.go && ./decodeBase64" C-m

tmux new-window -t backend-go:2
