#!/bin/bash

## Start Docker Containers
$HOME/scripts/FR-DOCKER_script && \
$HOME/scripts/SSD-DOCKER_script

## Prepare tmux windows For Monitoring
tmux new -s core-fr -d
for i in {1..4}
do
	tmux new-window -t core-fr:$i
done

## Execute Programs Inside Docker Containers, Using tmux
tmux send-keys -t core-fr:0 "docker exec -it api-recognition python3 fr_api.py" C-m
tmux send-keys -t core-fr:1 "docker exec -it api-recognition \
python3 -m model_server.runserver lib/serving_onnx.py" C-m
# sleep 300
tmux send-keys -t core-fr:2 "docker exec -it api-recognition python3 CSV_Generator.py" C-m
# sleep 300
tmux send-keys -t core-fr:3 "docker exec -it api-recognition python3 Mask_Generator.py" C-m
