#!/bin/bash
dbname=facever
dbfilename="facever.sql"
sshpass -p adminRKB ssh ubuntu@192.168.4.24 "PGPASSWORD=facever pg_dump -U facever -h localhost $dbname" | \
# $dbfilename &&
PGPASSWORD=facever psql -U facever -d $dbname
